### ISSUE TITLE
chunk overlaps and pruning of the subgraphs

### ISSUE THREAD

**Issue by ekg** [pangenome/gfalace#1]
We need to be able to have the subgraphs which are merging overlap. This is done to eliminate boundary effects. And we'll have to make sure this can be handled in this code.

**Comment by baozg** [comment]
Fow now, did the range from different subgraph should avoid he overlap?

**Comment by AndreaGuarracino** [comment]
With https://github.com/pangenome/gfalace/pull/2 we support any kind of partitioning. Overlapping paths just remain in the final combined graph. I'll implement a trimming operation to manage the overlap while keeping things easy.
