### ISSUE TITLE
gfa-list as input

### ISSUE THREAD

**Issue by baozg** [pangenome/gfalace#3]
I have about ~10000 gfa, merge them by `-g gfa1 gfa2 .... gfa10000` could be very hard to control. Is it possible to merge them as list? Like `samtools merge` could accept space delimited bam or bamlist. 

Another question, do `gfalace` need the order of gfa ? Or it should be sorted by paths ranges

**Comment by AndreaGuarracino** [comment]
I don't use it that way, but just with

```shell
gfalace -g *.gfa -o combined.gfa
```

I've updated the README with this example.

No order is assumed or required, the paths are in command!

**Comment by baozg** [comment]
Not accept `gfa.gz`?

**Comment by AndreaGuarracino** [comment]
Just implemented!
